-- 2FA (TOTP + recovery codes). Append-only: V1-V9 are applied and immutable (Flyway checksum),
-- so every change is a NEW file. ddl-auto=validate — these columns/tables must match the entities
-- (User.twoFactorEnabled/twoFactorSecret, TwoFactorRecoveryCode, TwoFactorChallenge) exactly.

-- users: enrolment flag + the AES-256-GCM ciphertext of the TOTP secret. two_factor_secret is
-- nullable and stays null until setup(); it holds base64(iv||ciphertext||tag), NEVER the raw secret.
-- The column is named to trip AuditSupport.isSensitive ("secret") so the @TrackChanges history of
-- users masks it to *** rather than recording the ciphertext.
alter table users add column two_factor_enabled boolean not null default false;
alter table users add column two_factor_secret text;

-- Recovery codes. Mirrors password_history (a per-user table of BCrypt hashes, verified by
-- iterating matches()): one row per plaintext code, stored only as a hash, single-use via
-- consumed_at. Column named *_hash so AuditSupport.isSensitive masks it. NO tenant_id column, on
-- purpose — see two_factor_challenges below for the reasoning; the row's tenant is authoritatively
-- the owning user's tenant.
create table two_factor_recovery_codes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  code_hash text not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create index ix_two_factor_recovery_codes_user on two_factor_recovery_codes(user_id);

-- Pre-login challenges. Mirrors refresh_tokens: an opaque, unguessable secret whose SHA-256 hash is
-- the only stored form, looked up by that unique hash, single-use (consumed_at), time-bounded
-- (expires_at). attempts_remaining is decremented on each wrong code and the challenge is retired at
-- zero. This is the artefact that stands between "password OK" and a minted token when 2FA is on.
--
-- DELIBERATELY NO tenant_id column (ArchitectureRules Rule 2 would then force a Hibernate @Filter,
-- which HibernateTenantFilterAspect enables per @Service call from TenantContext). The verify
-- endpoint is anonymous: TenantContext is driven off an OPTIONAL X-Tenant header, so a filter would
-- make a legitimate tenant user's challenge invisible whenever that header is absent — fail-CLOSED on
-- the happy path. refresh_tokens, the artefact this table mirrors, carries no tenant_id for exactly
-- this reason: the token_hash is a 256-bit secret, the row is always resolved through user_id, and
-- the tenant is taken from User.tenant_id when the token is minted (JwtService reads it there). See
-- RISK-REGISTER.
create table two_factor_challenges (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  token_hash text not null,
  expires_at timestamptz not null,
  attempts_remaining int not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint uq_two_factor_challenges_hash unique (token_hash)
);
create index ix_two_factor_challenges_user on two_factor_challenges(user_id);
