-- RLS taban cizgisi, Adim 1 — RLS'in ON KOSULU: veritabani kimlik ayrimi.
-- Otorite: ADR-0018 (host gorunurlugu) baslangic kosullari; muafiyet kumesi ADR-0019.
--
-- BU DOSYA POLITIKA EKLEMEZ. `ENABLE/FORCE ROW LEVEL SECURITY` ve `CREATE POLICY` bilincli
-- olarak yok; onlar Adim 4'un tablo-grubu migration'larina ait (V12, V13). Burada yalnizca
-- uygulamanin baglandigi KIMLIK, Flyway'in kullandigi kimlikten ayrilir.
--
-- NEDEN ONCE BU: bugune kadar uygulama ve Flyway ayni kimlikle baglaniyordu (`DB_USER:zero`).
-- O hâlde RLS eklense bile KANITLANAMAZ:
--   * tablonun owner'i FORCE ROW LEVEL SECURITY olmadan kendi politikasini ATLAR,
--   * superuser her hâlukârda ATLAR.
-- Yani izolasyon testleri politika hic calismadan yesil doner — yalanci yesil. Ayrim
-- yapilmadan yazilan politika, olcusu olmayan bir korumadir.
--
-- ⚠️ BU MIGRATION'I FLYWAY OWNER/SUPERUSER ILE KOSAR (`spring.flyway.user`, application.yml).
-- CREATE ROLE yetkisi oradan gelir; `zero_app`'in kendisi NOCREATEROLE'dur ve bu dosyayi
-- kosamaz. Kimlik ayrimi bu dosyanin ON KOSULU'dur, sonucu degil.
--
-- ⚠️ ASAGIDAKI SIFRE COMMIT'LIDIR, YANI HERKESE ACIKTIR. Dev ve CI'in deterministik bir
-- degere ihtiyaci var; bunun bedeli, sifrenin repo gecmisinde public olmasi. Korumasi iki
-- katmanli:
--   1) `AppDbCredentialsValidator` — `prod` profilinde datasource sifresi bu deger ise
--      UYGULAMA ACILMAZ (JwtSecretValidator deseni: commit'li sirri prod'da reddet).
--   2) Bu dosya var olan bir rolu ASLA `ALTER ROLE ... PASSWORD` ile ezmez. Prod'da rolu
--      operator ILK MIGRATE'DEN ONCE gercek bir sifreyle yaratir; asagidaki blok o rolu
--      gorup yaratmayi atlar. Tersi (kosulsuz ALTER) prod sifresini sessizce public bir
--      degere dusururdu — bu yuzden kosullu.
--      Rol prod'da onceden yaratilmadiysa: `ALTER ROLE zero_app PASSWORD '<yeni>'` ve
--      `DB_PASSWORD` guncellenir; validator zaten eski sifreyle acilisa izin vermez.
--
-- ⚠️ CREATE ROLE KUME (cluster) SEVIYESINDEDIR, veritabanina ait DEGILDIR. Ayni kumede ikinci
-- bir veritabanina bu migration seti uygulanirsa rol coktan vardir. Idempotent olmasi bu
-- yuzden sart, "temizlik" degil.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'zero_app') THEN
    CREATE ROLE zero_app LOGIN PASSWORD 'zero_app_dev_password'
      NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  END IF;
END $$;

-- NOBYPASSRLS'in anlami: Adim 4'te politikalar eklendiginde bu rol onlardan MUAF OLAMAZ.
-- Rol tanimindan bunu dusurmek, tek satirlik bir degisiklikle butun RLS yuzeyini kapatir.

GRANT USAGE ON SCHEMA public TO zero_app;

-- MEVCUT nesneler. Bu migration seti icindeki en son dosya oldugu icin buradaki `ALL TABLES`
-- semadaki her tabloyu kapsar; `flyway_schema_history` de dahildir ve bu BILINCLIDIR:
-- MigrationGuardIT o tabloyu UYGULAMA datasource'u uzerinden okur.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO zero_app;
-- Bugun tum PK'lar `generated by default as identity` — ortuk sequence'lar tablo iznine
-- baglidir, yani bu satir su an gereksiz. Yine de yaziliyor: ileride bir `serial` ya da acik
-- `CREATE SEQUENCE` eklenirse eksik USAGE, ilk INSERT'te `permission denied for sequence`
-- olarak ve migration'dan cok sonra patlar.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO zero_app;

-- GELECEKTEKI nesneler — atlanirsa BUNDAN SONRAKI HER YENI TABLO app rolune GORUNMEZ olur.
-- Hata migration'da degil, o tabloya ilk dokunan istekte `permission denied for table X`
-- olarak cikar; yani sema degisikligini yapan kisi degil, aylar sonra baska biri gorur.
-- (Yukaridaki `ALL TABLES` yalnizca simdi var olanlari kapsar — gelecege bakmaz.)
--
-- ⚠️ DEFAULT PRIVILEGES, ALTER'i KOSAN ROLE bagli tanimlanir: yalnizca `spring.flyway.user`
-- ile ayni rolun yarattigi nesneler icin gecerlidir. Migration kimligi bir gun degisirse
-- bu iki satir YENI rol icin tekrar kosulmalidir, aksi halde ayni sessiz izin bosluguna
-- geri donulur.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO zero_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO zero_app;
