-- Kullanici daveti. Tablo ve RLS politikasi TEK dosyada dogar: RlsCoverageIT her
-- `tenant_id` tasiyan tabloda ENABLE + FORCE + politika arar ve muafiyet kumesi kapalidir
-- (ADR-0019, kural 4).
--
-- TASARIM NOTLARI (kodun soyleyemedikleri):
--
-- * `token_hash` — ham davet token'i YALNIZ e-postada yasar; DB SHA-256 hex'ini tutar.
--   Desen, V14'un reset/confirmation kodlarina uyguladigi desenle AYNIDIR (R-44): davet token'i
--   bir HESAP YARATMA yetkisidir ve tablo dokumu sizarsa duz token dogrudan oturuma cevrilir;
--   hash'lenmis hali cevrilmez.
--
-- * `status` uc deger tasir: PENDING | ACCEPTED | REVOKED. "EXPIRED" ayri bir durum DEGIL —
--   sure asimi `expires_at` uzerinden okunur (PENDING + gecmis tarih). Ayri durum, onu yazacak
--   bir zamanlanmis is gerektirirdi; is `@Component` olurdu ve GUC yazmadigi icin politikali bu
--   tabloda 0 satir gorup sessizce "basarili" donerdi (R-46'nin tam sinifi).
--
-- * Kismi UNIQUE indexler yalniz PENDING satirlari kapsar: ayni adrese/kullanici adina ikinci
--   BEKLEYEN davet 409'dur; kabul edilmis/iptal edilmis eski davetler yeniden davete engel
--   degildir. `nulls not distinct` (PG15+) host davetlerinde (`tenant_id IS NULL`) de tekligi
--   korur — duz UNIQUE, NULL'lari ayri saydigi icin host tarafinda sinirsiz cift davete izin
--   verirdi.
--
-- * RLS politikasi V12'nin `organization_units` seklidir: host-global okuma kolu YOK. Gerekce
--   ayni: kiraci baglaminda host davetini okuyan mesru bir yol yok — anonim kabul akisi
--   (`InvitationService.accept`) TenantContext'siz kosar, aspect GUC'a `app.is_host='on'` yazar
--   ve host kolundan gecer; kiraci CRUD'u kendi koluyla sinirlidir.
create table user_invitations (
    id                  bigint generated by default as identity primary key,
    tenant_id           bigint references tenants (id),
    username            varchar(64)  not null,
    email               varchar(256) not null,
    role_names          varchar(1024) not null,
    token_hash          varchar(128) not null,
    status              varchar(20)  not null,
    expires_at          timestamptz  not null,
    invited_by_user_id  bigint       not null references users (id),
    accepted_user_id    bigint       references users (id),
    created_at          timestamptz  not null,
    created_by          varchar(64),
    updated_at          timestamptz,
    updated_by          varchar(64)
);

create index ix_user_invitations_tenant on user_invitations (tenant_id);

create unique index uq_user_invitations_token on user_invitations (token_hash);

create unique index uq_user_invitations_pending_email
    on user_invitations (tenant_id, lower(email)) nulls not distinct
    where status = 'PENDING';

create unique index uq_user_invitations_pending_username
    on user_invitations (tenant_id, lower(username)) nulls not distinct
    where status = 'PENDING';

-- RLS — V12 `organization_units` deseniyle birebir (host-global kol yok, asimetri yok).
alter table user_invitations enable row level security;
alter table user_invitations force  row level security;
drop policy if exists tenant_isolation on user_invitations;
create policy tenant_isolation on user_invitations
  using      (tenant_id = nullif(current_setting('app.current_tenant', true), '')::bigint
              or current_setting('app.is_host', true) = 'on')
  with check (tenant_id = nullif(current_setting('app.current_tenant', true), '')::bigint
              or current_setting('app.is_host', true) = 'on');
grant select, insert, update, delete on user_invitations to zero_app;
