-- P2''-A: portal'dan yönetilebilir sağlayıcı kimlik bilgileri (ADR-0020).
-- Satır başına BİR sağlayıcı; kimlik bilgileri TEK ciphertext olarak durur:
-- credentials_secret = FieldEncryptionService.encrypt(JSON{alan->değer}) — AES-256-GCM,
-- zero.crypto.field-key (PROD-R49 ile aynı anahtar). Düz metin sütunu YOK ve olmayacak:
-- API'ye geri gönderim geri çevrilebilirlik gerektirdiği için hash değil şifreleme (ADR-0020).
--
-- HOST-GLOBAL tablo: tenant_id YOK, bilerek. Sağlayıcı hesabı kurulumun (host'un) hesabıdır,
-- kiracının değil. tenant_id taşımadığı için RlsCoverageIT bu tabloyu zaten taramaz —
-- ADR-0019 muafiyet listesine giriş GEREKMEZ; telafi edici kontrol, tabloya dokunan tek yüzeyin
-- Side.HOST 'billing.credentials.manage' izni arkasında olmasıdır (ADR-0015 deseni).
--
-- display_order: checkout başlatmadaki failover sırası (küçük önce). enabled yalnız YENİ
-- checkout'ları kapatır; webhook/mutabakat yüzeyi kimlik bilgisi durdukça açık kalır —
-- uçuştaki ödemeler kendi sağlayıcısında bitmek zorundadır ("disabled = yeni checkout'a
-- kapalı, webhook'a değil", BillingProviderAvailability).

create table billing_provider_credentials (
  id bigint generated by default as identity primary key,
  provider varchar(32) not null,                         -- BillingProvider.id(): "paytr" | "iyzico" | "stripe"
  enabled boolean not null default false,                -- yalnız yeni checkout'lar için; webhook yüzeyini KAPATMAZ
  display_order int not null default 0,                  -- failover sırası, küçük önce
  credentials_secret text,                               -- base64([IV||ct||tag]) — alanların JSON'u tek ciphertext
  created_at timestamptz not null,
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_billing_provider_credentials_provider unique (provider)
);

grant select, insert, update, delete on billing_provider_credentials to zero_app;
