create table tenants (
  id bigint generated by default as identity primary key,
  name varchar(30) not null,
  display_name varchar(128) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_tenants_name unique (name)
);

create table users (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenants(id),
  username varchar(64) not null,
  email varchar(256) not null,
  password_hash varchar(256) not null,
  active boolean not null default true,
  failed_login_attempts int not null default 0,
  lockout_end_at timestamptz,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_users_tenant_username unique nulls not distinct (tenant_id, username)
);
create index ix_users_tenant on users(tenant_id);

create table roles (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenants(id),
  name varchar(64) not null,
  is_static boolean not null default false,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_roles_tenant_name unique nulls not distinct (tenant_id, name)
);

create table role_permissions (
  role_id bigint not null references roles(id) on delete cascade,
  permission varchar(128) not null,
  primary key (role_id, permission)
);

create table user_roles (
  user_id bigint not null references users(id) on delete cascade,
  role_id bigint not null references roles(id) on delete cascade,
  primary key (user_id, role_id)
);

create table refresh_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  token_hash varchar(64) not null,
  expires_at timestamptz not null,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  constraint uq_refresh_tokens_hash unique (token_hash)
);
create index ix_refresh_tokens_user on refresh_tokens(user_id);
