-- users: ABP profil + hesap alanları
alter table users add column name varchar(64);
alter table users add column surname varchar(64);
alter table users add column phone_number varchar(32);
alter table users add column deleted boolean not null default false;
alter table users add column deleted_at timestamptz;
alter table users add column email_confirmed boolean not null default false;
alter table users add column email_confirmation_code varchar(128);
alter table users add column password_reset_code varchar(128);
alter table users add column should_change_password boolean not null default false;
alter table users add column last_password_change_at timestamptz;
alter table users add column profile_picture_id bigint;   -- files modülü F3; şimdilik boş

-- roles: görünen ad + varsayılan rol
alter table roles add column display_name varchar(128);
alter table roles add column is_default boolean not null default false;
update roles set display_name = name where display_name is null;
alter table roles alter column display_name set not null;

-- password history (son N şifre tekrarını engelle)
create table password_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  password_hash varchar(256) not null,
  created_at timestamptz not null default now()
);
create index ix_password_history_user on password_history(user_id);

-- organization units (ABP materialized-path: code örn '00001.00003')
create table organization_units (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenants(id),
  parent_id bigint references organization_units(id),
  code varchar(95) not null,
  display_name varchar(128) not null,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64)
);
create index ix_ou_tenant on organization_units(tenant_id);
create index ix_ou_code on organization_units(code);

create table user_organization_units (
  user_id bigint not null references users(id) on delete cascade,
  organization_unit_id bigint not null references organization_units(id) on delete cascade,
  primary key (user_id, organization_unit_id)
);

-- hiyerarşik ayarlar
create table settings (
  id bigint generated by default as identity primary key,
  scope varchar(16) not null,            -- APPLICATION | TENANT | USER
  scope_id bigint,                       -- TENANT→tenantId, USER→userId, APPLICATION→null
  name varchar(128) not null,
  value varchar(2000),
  constraint uq_settings unique nulls not distinct (scope, scope_id, name)
);
create index ix_settings_lookup on settings(scope, scope_id, name);

-- HTTP audit log
create table audit_logs (
  id bigint generated by default as identity primary key,
  tenant_id bigint,
  user_id bigint,
  username varchar(64),
  service_name varchar(256),
  method_name varchar(256),
  parameters varchar(2000),
  execution_time timestamptz not null,
  execution_duration_ms int not null,
  client_ip varchar(64),
  browser_info varchar(512),
  http_method varchar(16),
  url varchar(512),
  http_status_code int,
  exception varchar(2000)
);
create index ix_audit_time on audit_logs(execution_time);
create index ix_audit_tenant_user on audit_logs(tenant_id, user_id);

-- entity change history (ABP EntityHistory paritesi)
create table entity_changes (
  id bigint generated by default as identity primary key,
  tenant_id bigint,
  user_id bigint,
  entity_type_name varchar(256) not null,
  entity_id varchar(64) not null,
  change_type varchar(16) not null,      -- CREATED | UPDATED | DELETED
  change_time timestamptz not null
);
create index ix_entity_changes_lookup on entity_changes(entity_type_name, entity_id);

create table entity_property_changes (
  id bigint generated by default as identity primary key,
  entity_change_id bigint not null references entity_changes(id) on delete cascade,
  property_name varchar(128) not null,
  original_value varchar(2000),
  new_value varchar(2000)
);
