-- in-app notification inbox (F3: WebSocket yok, polling ile okunur)
create table user_notifications (
  id bigint generated by default as identity primary key,
  tenant_id bigint,
  user_id bigint not null references users(id) on delete cascade,
  notification_name varchar(128) not null,
  level varchar(16) not null default 'INFO',
  title varchar(256) not null,
  body varchar(2000),
  data varchar(2000),
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index ix_user_notifications_user on user_notifications(user_id, is_read);
