-- F5 Slice A: SaaS ticari katman — editions, features, subscriptions.
-- payments / invoices / webhook_events Slice C'de eklenir (F5-ARCHITECTURE §2).
-- Konvansiyon: identity PK, timestamptz, para numeric(19,4), uq_/ix_ adlandırma.

create table editions (
  id bigint generated by default as identity primary key,
  name varchar(64) not null,
  display_name varchar(128) not null,
  description varchar(512),
  monthly_price numeric(19,4),                 -- null + annual_price null => free edition
  annual_price numeric(19,4),
  currency varchar(3),
  trial_day_count int not null default 0,
  grace_day_count int not null default 0,
  expiring_edition_id bigint references editions(id),   -- downgrade hedefi; free olmak zorunda
  is_active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_editions_name unique (name)
);
create index ix_editions_active on editions(is_active, sort_order);

create table edition_features (
  id bigint generated by default as identity primary key,
  edition_id bigint not null references editions(id) on delete cascade,
  feature_name varchar(128) not null,
  value varchar(2000),
  constraint uq_edition_features unique (edition_id, feature_name)
);
create index ix_edition_features_edition on edition_features(edition_id);

-- host override: tenant'a özel feature değeri (çözümleme zincirinin en üstü)
create table tenant_features (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  feature_name varchar(128) not null,
  value varchar(2000),
  constraint uq_tenant_features unique (tenant_id, feature_name)
);
create index ix_tenant_features_tenant on tenant_features(tenant_id);

create table subscriptions (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  edition_id bigint not null references editions(id),
  status varchar(24) not null,                 -- TRIALING | ACTIVE | GRACE | EXPIRED | CANCELLED | PENDING_PAYMENT
  billing_period varchar(16),                  -- MONTHLY | ANNUAL | null (free)
  price_amount numeric(19,4),                  -- SNAPSHOT: edition fiyatı sonradan değişse abone etkilenmez
  price_currency varchar(3),                   -- SNAPSHOT
  trial_end_at timestamptz,
  current_period_end_at timestamptz,
  grace_end_at timestamptz,
  cancelled_at timestamptz,
  external_ref varchar(128),                   -- billing provider aboneliği (Slice C)
  provider varchar(32),                        -- "manual" | "stripe" | ... (billing sağlayıcı)
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_subscriptions_tenant unique (tenant_id)   -- tenant başına tek abonelik
);
create index ix_subscriptions_status_period on subscriptions(status, current_period_end_at);
create index ix_subscriptions_edition on subscriptions(edition_id);

-- denetlenebilir yaşam döngüsü izi (audit modülünden bağımsız domain kaydı)
create table subscription_events (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references subscriptions(id) on delete cascade,
  from_status varchar(24),
  to_status varchar(24) not null,
  reason varchar(64),
  occurred_at timestamptz not null default now(),
  actor varchar(64)
);
create index ix_subscription_events_subscription on subscription_events(subscription_id, occurred_at);
