-- P2-A: Stripe billing intake — payments + webhook_events (F5-ARCHITECTURE §2, Slice C tables).
-- Konvansiyon: identity PK, timestamptz, para numeric(19,4), uq_/ix_/ck_ adlandırma.
-- saas modülü host-scope'tur (ADR-0015): tenant @Filter yok, tenant_id açık sütun.

create table payments (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenants(id) on delete cascade,
  subscription_id bigint not null references subscriptions(id) on delete cascade,
  target_edition_id bigint references editions(id),      -- null: ödeme mevcut paketi yeniler, paket değiştirmez
  amount numeric(19,4) not null,
  currency varchar(3) not null,
  period varchar(16),                                    -- MONTHLY | ANNUAL (snapshot; abonelikle aynı sözlük)
  status varchar(16) not null,
  external_session_id varchar(255),                      -- Stripe checkout session id; UNIQUE = webhook -> payment eşlemesi
  external_payment_id varchar(255),                      -- Stripe payment intent id (ödeme onayında dolar)
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  created_by varchar(64),
  updated_at timestamptz,
  updated_by varchar(64),
  constraint uq_payments_external_session unique (external_session_id),
  constraint ck_payments_status check (status in ('NOT_PAID', 'PAID', 'FAILED', 'CANCELLED'))
);
create index ix_payments_tenant on payments(tenant_id);
create index ix_payments_subscription on payments(subscription_id);

-- Sağlayıcı webhook'larının dedup defteri. UNIQUE (provider, event_id) İDEMPOTENSİNİN KENDİSİDİR:
-- BillingWebhookService "insert ... on conflict do nothing" ile yazar; 0 satır = mükerrer teslimat
-- = işlemeden 200. Kaynak sistemin ölçülen hatası (mükerrer -> 400 -> sonsuz Stripe retry) bu
-- kısıtla kapanır.
create table webhook_events (
  id bigint generated by default as identity primary key,
  provider varchar(32) not null,                         -- "stripe" | ...
  event_id varchar(255) not null,                        -- sağlayıcının event id'si (evt_...)
  event_type varchar(64) not null,                       -- eşlenmiş tip (CHECKOUT_COMPLETED | RECURRING_PAYMENT_SUCCEEDED | UNKNOWN)
  payload text not null,                                 -- imzalı ham gövde; sonradan inceleme/backfill için
  received_at timestamptz not null,
  processed_at timestamptz,
  status varchar(16) not null,
  constraint uq_webhook_events_provider_event unique (provider, event_id),
  constraint ck_webhook_events_status check (status in ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED'))
);
